# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-05 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='full_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
