# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-24 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(null=True, upload_to='Products/images/'),
        ),
    ]
