# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-25 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20200425_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(null=True, upload_to='Products/images/'),
        ),
    ]
